### PR TITLE
Add a getter for the endpoint

### PR DESCRIPTION
**Pull request by TheKeymaster**
Instead of using `$this->endpoint` directly, use a getter.

### CODE REVIEW

**Comment by TheKeymaster** [comment]
Tests need to be fixed... I'm on it.

**Comment by TheKeymaster** [comment]
@dolejska-daniel Even when I remove the change I still get the Build failure `Request: Unauthorized. (Unauthorized)`. Is this expected or how can I prevent this from happening?

**Comment by dolejska-daniel** [comment]
Hi @TheKeymaster,

thanks for your contribution. Since [builds of `master` branch are without errors](https://travis-ci.org/dolejska-daniel/riot-api/builds/408128629) I assume there are more problems with your code. Please review it once more and try to fix them.

Use Travis to verify that your code works.

Have a nice day,
Daniel

**Comment by dolejska-daniel** [comment]
I'm closing this PR, since there were no updates.

**Pull request closed without merging**
